fix AttributeError: 'Context' object has no attribute 'session'
Occurred when jobmanager.stop() is called before loopmanager.start()

- set context.session to None on init
- set running to True in jobmanager.run()